---
- project:
    check:
      jobs:
        - ansible-tox-linters
        - ansible-tox-molecule:
            required-projects:
              - name: github.com/ansible/ansible
                override-checkout: stable-2.9
              - name: github.com/ansible-security/ids_config
    gate:
      jobs:
        - ansible-tox-linters
        - ansible-tox-molecule:
            required-projects:
              - name: github.com/ansible/ansible
                override-checkout: stable-2.9
              - name: github.com/ansible-security/ids_config
