---
dependency:
  name: shell
  command: ./tools/install_roles.sh
  enabled: true
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment: { container: docker }
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
