---
dependency:
  name: shell
  command: ./tools/install_roles.sh
  enabled: true
driver:
  name: podman
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
    privileged: true
    command: "/usr/sbin/init"
    tty: true
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
